CREATE DATABASE wordpress CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER 'wordpress'@'10.22.2.11' IDENTIFIED BY 'REPLACE_WORDPRESS_DB_PASSWORD';
GRANT ALL PRIVILEGES ON wordpress.* TO 'wordpress'@'10.22.2.11';
FLUSH PRIVILEGES;
